import {
  FaHtml5,
  FaCss3Alt,
  FaJsSquare,
  FaReact,
  FaNodeJs,
  FaBootstrap,
  FaGitAlt,
  FaGithub,
  FaDatabase,
} from "react-icons/fa";
import {
  SiRedux,
  SiAxios,
  SiTailwindcss,
  SiPyup,
  SiNextdotjs,
  SiVite,
  SiExpress,
  SiGraphql,
  SiPostgresql,
  SiMongodb,
  SiSqlite,
  SiKnexdotjs,
  SiFirebase,
  SiJest,
  SiCypress,
  SiPuppeteer,
  SiPostman,
  SiInsomnia,
  SiHttpie,
  SiEslint,
  SiOpenai,
  SiHeroku,
  SiRailway,
  SiRender,
  SiNetlify,
  SiVercel,
  SiFigma,
} from "react-icons/si";

// Main skills list with icons
export const skills = [
  { name: "HTML5", icon: <FaHtml5 className="text-orange-500" /> },
  { name: "CSS3", icon: <FaCss3Alt className="text-blue-500" /> },
  { name: "JavaScript", icon: <FaJsSquare className="text-yellow-400" /> },
  { name: "React", icon: <FaReact className="text-cyan-400" /> },
  { name: "Node.js", icon: <FaNodeJs className="text-green-600" /> },
  {
    name: "Express",
    icon: <SiExpress className="text-black dark:text-white" />,
  },
  { name: "SQL", icon: <FaDatabase className="text-indigo-500" /> },
  { name: "PostgreSQL", icon: <SiPostgresql className="text-blue-700" /> },
  { name: "MongoDB", icon: <SiMongodb className="text-green-600" /> },
  { name: "Redux", icon: <SiRedux className="text-purple-500" /> },
  {
    name: "Next.js",
    icon: <SiNextdotjs className="text-black dark:text-white" />,
  },
  { name: "RESTful API", icon: <FaDatabase className="text-blue-300" /> },
  { name: "GraphQL", icon: <SiGraphql className="text-pink-500" /> },
  { name: "Git", icon: <FaGitAlt className="text-orange-600" /> },
  {
    name: "GitHub",
    icon: <FaGithub className="text-gray-900 dark:text-white" />,
  },
  { name: "Tailwind CSS", icon: <SiTailwindcss className="text-cyan-400" /> },
  { name: "Bootstrap", icon: <FaBootstrap className="text-purple-600" /> },
  { name: "Vite", icon: <SiVite className="text-yellow-400" /> },
  { name: "Axios", icon: <SiAxios className="text-sky-500" /> },
  { name: "Yup", icon: <SiPyup className="text-yellow-700" /> },
  { name: "Jest", icon: <SiJest className="text-red-500" /> },
  { name: "Cypress", icon: <SiCypress className="text-green-400" /> },
  { name: "Puppeteer", icon: <SiPuppeteer className="text-yellow-500" /> },
  { name: "Knex.js", icon: <SiKnexdotjs className="text-orange-400" /> },
  { name: "SQLite", icon: <SiSqlite className="text-blue-400" /> },
  { name: "Firebase", icon: <SiFirebase className="text-yellow-500" /> },
  { name: "Netlify", icon: <SiNetlify className="text-teal-400" /> },
  { name: "Vercel", icon: <SiVercel className="text-black dark:text-white" /> },
  { name: "Heroku", icon: <SiHeroku className="text-purple-800" /> },
  {
    name: "Railway",
    icon: <SiRailway className="text-black dark:text-white" />,
  },
  { name: "Render", icon: <SiRender className="text-blue-400" /> },
  { name: "Postman", icon: <SiPostman className="text-orange-500" /> },
  { name: "Insomnia", icon: <SiInsomnia className="text-purple-600" /> },
  { name: "HTTPie", icon: <SiHttpie className="text-green-500" /> },
  { name: "ESLint", icon: <SiEslint className="text-purple-500" /> },
  { name: "Figma", icon: <SiFigma className="text-pink-500" /> },
  { name: "OpenAI", icon: <SiOpenai className="text-green-600" /> },
];

// Skills without icons (just names)
export const skillsNoIcon = [
  "Authentication",
  "Authorization",
  "JWT",
  "bcrypt",
  "Validation",
  "CRUD",
  "Debugging",
  "Algorithms",
  "Code Refactoring",
  "Architecture",
  "Deployment",
  "Webpack",
  "Babel",
  "Cache",
  "Zustand",
  "Supertest",
  "Playwright",
  "Morgan",
  "SEO",
  "VS Code",
  "No-Code Automation",
  "Agile Project Management",
];
